// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBnFMNEbttvEiNdUSGt73Ih7wGqHgIvVE',
    appId: '1:118362286247:web:88dee293dc7fc9b81b9382',
    messagingSenderId: '118362286247',
    projectId: 'taskman-dev-shoyo-53266',
    authDomain: 'taskman-dev-shoyo-53266.firebaseapp.com',
    storageBucket: 'taskman-dev-shoyo-53266.firebasestorage.app',
    measurementId: 'G-HMPVJDLLPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCasl6mU5b-evqe2v-apTYBdcjBfGvt4Zs',
    appId: '1:118362286247:android:930f86fbe9fcdce21b9382',
    messagingSenderId: '118362286247',
    projectId: 'taskman-dev-shoyo-53266',
    storageBucket: 'taskman-dev-shoyo-53266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwb1of-EMDi-xI-wO4CXGfxL19FtmC0lQ',
    appId: '1:118362286247:ios:2d9940a3edae6a961b9382',
    messagingSenderId: '118362286247',
    projectId: 'taskman-dev-shoyo-53266',
    storageBucket: 'taskman-dev-shoyo-53266.firebasestorage.app',
    iosBundleId: 'com.example.taskman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwb1of-EMDi-xI-wO4CXGfxL19FtmC0lQ',
    appId: '1:118362286247:ios:2d9940a3edae6a961b9382',
    messagingSenderId: '118362286247',
    projectId: 'taskman-dev-shoyo-53266',
    storageBucket: 'taskman-dev-shoyo-53266.firebasestorage.app',
    iosBundleId: 'com.example.taskman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBnFMNEbttvEiNdUSGt73Ih7wGqHgIvVE',
    appId: '1:118362286247:web:806daedb3ba6f5e71b9382',
    messagingSenderId: '118362286247',
    projectId: 'taskman-dev-shoyo-53266',
    authDomain: 'taskman-dev-shoyo-53266.firebaseapp.com',
    storageBucket: 'taskman-dev-shoyo-53266.firebasestorage.app',
    measurementId: 'G-5TWFSLP4YG',
  );
}
